baseurl = "http://satechdad.com"
languageCode = "en-us"
title = "San Antonio Tech Dads"
theme = "material-design"
paginate = 5
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  description = "A podcast about kids, tech, the city of San Antonio. And dad jokes." # optional
  twitter = "satechdad" # optional
  # facebook = "Your facebook Name" # optional
  # gplus = "Your Google+ profile name" # optional
  # linkedin = "Your LinkedIn Name" # optional
  headerCover = "images/SaTechDad-Podcast-bg.png" # optional
  footerCover = "images/satechdad-bg.png" # optional
  # googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
