baseurl = "http://www.satechdad.com"
languageCode = "en-us"
title = "San Antonio Tech Dads"
theme = "material-design"
paginate = 5
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  description = "A podcast about kids, tech, the city of San Antonio. And dad jokes." # optional
  twitter = "satechdad" # optional
  # facebook = "Your facebook Name" # optional
  # gplus = "Your Google+ profile name" # optional
  # linkedin = "Your LinkedIn Name" # optional
  headerCover = "http://drops.albush.com/SaTechDad-Podcast-bg.png" # optional
  footerCover = "http://drops.albush.com/SaTechDad-Podcast-bg.png" # optional
  googleAnalyticsUserID = "UA-68370949-1"

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
